apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-hkube
  labels:
    app: health-hkube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: health-hkube
  template:
    metadata:
      labels:
        app: health-hkube
    spec:    
      containers:
        - name: flask
          image: ${imageName}
          env:
          -  name: MASTER_CLUSTER_IP
             value: $(masterClusterIP)
          -  name: REDIS_REPLICAS
             value: $(redis_replicas)
          -  name: ETCD_REPLICAS
             value: $(etcd_replicas)
          resources:  
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 5000
      serviceAccountName: algorithm-operator-serviceaccount
      serviceAccount: algorithm-operator-serviceaccount    