apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-hkube
  labels:
    app: health-hkube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: health-hkube
  template:
    metadata:
      labels:
        app: health-hkube
    spec:    
      containers:
        - name: flask
          image: flask:4.2
          env:
          -  name: MASTER_CLUSTER_IP
             value: 'https://192.168.49.2:8443'
          -  name: REDIS_REPLICAS
             value: '3'
          -  name: ETCD_REPLICAS
             value: '3'
          resources:  
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 5000
      serviceAccountName: cleanup-serviceaccount
      serviceAccount: cleanup-serviceaccount