apiVersion:  networking.k8s.io/v1
kind: Ingress
metadata:
  name: health-hkube
  labels:
    app: health-hkube
spec:
  rules:
    - http:
        paths:
        - path: /
          backend:
            service:
              name: health-hkube
              port:
                number: 5000
          pathType: Prefix